services:
  vault:
    container_name: ${VAULT_CONTAINER_NAME}
    image: ${VAULT_IMAGE_NAME}:${VAULT_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      VAULT_ADDR: 'http://localhost:8200'
      TZ: ${TIMEZONE}
    ports:
      - ${VAULT_HTTP_PORT}:8200
    volumes:
      - default:/vault/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8200/v1/sys/health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${VAULT_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${VAULT_CONTAINER_NAME}_data
    driver: local