version: '3.9'
services:
  web:
    image: vault:1.13.3
    container_name: vault
    restart: always
    ports:
      - ${APP_PORT}:8200
    networks:
      - default
    volumes:
      - data:/vault/data
      - ./data:/vault/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VAULT_ADDR: 'http://localhost:8200'

networks:
  default:
    name: docker_hashicorp_vault_network
    driver: bridge

volumes:
  data:
    name: docker_hashicorp_vault_data
    driver: local
