version: '3.9'
services:
  web:
    image: vault:latest
    container_name: vault
    restart: always
    ports:
      - ${APP_PORT}:8200
    networks:
      - default
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VAULT_ADDR: 'http://localhost:8200'
      VAULT_DEV_ROOT_TOKEN_ID: 'vault-plaintext-root-token'

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
